---
title: "LS"
author: "Yaochen Zhu"
date: "April 4, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
```


```{r}
senti <- read.csv("~/GitHub/CVEngineer_Bootcamp/sentiment_sentence.csv")
char <- read.csv("~/GitHub/CVEngineer_Bootcamp/character_sentence.csv")
ends <- read.csv("~/GitHub/CVEngineer_Bootcamp/chapter_ends.csv")
```


```{r message=FALSE, warning=FALSE}
library(reshape2)
library(ggplot2)

#row.names(senti) = strsplit(toString(senti[,1]), ',')[[1]]
senti_invest = senti[2,-1] # anger
#senti_compound[,darcy_app]

melted_senti <- melt(senti)
melted_senti[,3] = (melted_senti[,3] != 0)
melted_senti[,3] = as.numeric(melted_senti[,3])

ggplot(melted_senti, aes(x = variable, y = X)) + 
  geom_raster(aes(fill=value)) + 
  scale_fill_gradient(low="skyblue", high="dodgerblue4") +
  labs(x="Sentences", y="Sentiments", title="Data Matrix for Sentence-Sentiment") +
  theme_bw() + theme(axis.text.x=element_text(size=9, angle=0, vjust=0.3),
                     axis.text.y=element_text(size=9),
                     plot.title=element_text(size=11)) +
  theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
  

```

```{r}
x = seq(-10, 10, by = 1)
y = 10*dnorm(x, mean = 0, sd = 1)

kernel <- function(id, one_d_data = senti_invest, weight = y, window = 21){
  smooth = 0
  if (id >= (window-1)/2 & id <= (dim(one_d_data)[2] - (window-1)/2)){
    smooth = sum(weight * one_d_data[1,(id-(window-1)/2):(id+(window-1)/2)])
  } else if (id < (window-1)/2) {
    smooth = sum(weight[((window+1)/2-id):window] * one_d_data[1,1:(id+(window-1)/2)])
  } else {
    length  = (window+1)/2 + dim(one_d_data)[2]-id
    smooth = sum(weight[1:length] * one_d_data[1,id-((window-1)/2):id-((window-1)/2)+length-1])
  }
  return(smooth)
}

```


```{r}
library(rlang)
library(glmnet)
library(matlib)
```


```{r}
melted_char <- melt(char)
melted_char[,3] = (melted_char[,3] != 0)
melted_char[,3] = as.numeric(melted_char[,3])

ggplot(melted_char, aes(x = variable, y = X)) + 
  geom_raster(aes(fill=value)) + 
  scale_fill_gradient(low="skyblue", high="dodgerblue4") +
  labs(x="Sentences", y="Character", title="Data Matrix for Character Appearance (Before Kernel Smoothing)") +
  theme_bw() + theme(axis.text.x=element_text(size=9, angle=0, vjust=0.3),
                     axis.text.y=element_text(size=9),
                     plot.title=element_text(size=11)) +
  theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())


senti_invest = senti[2,-1] # investiage the positive sentiment contribution

contribution = matrix(0L, nrow = dim(char[,-1])[1], ncol = dim(char[,-1])[2])

for (i in 1:dim(char)[1]){
  
char_app = which(char[i,-1] == 1)



contribution[i, char_app] = sapply(char_app, kernel) # on this index apply the kernel

}


contribution_plot = duplicate(contribution, shallow = FALSE)
contribution_plot[which(contribution_plot >= 1)] = 1
melt_con = melt(contribution_plot)

ggplot(melt_con, aes(x = Var2, y = Var1)) + 
  geom_raster(aes(fill=value)) + 
  scale_fill_gradient(low="skyblue", high="dodgerblue4") +
  labs(x="Sentences", y="Character", title="Data Matrix for Nugative Sentiment Contribution (After Kernel Smoothing)") +
  theme_bw() + theme(axis.text.x=element_text(size=9, angle=0, vjust=0.3),
                     axis.text.y=element_text(size=9),
                     plot.title=element_text(size=11)) +
  theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
# contribution 14*5584

# some outlier

sum(contribution >= 10) # 20
sum(contribution >= 300) # 2
sum(contribution >= 1) # 20

# Winsernize the data, the upper bound is 10
# contribution[which(contribution >= )] = 100

```

```{r}

contribution[contribution >= 5] = 5


# ridge regression
start_chap = 1
end_chap = 61
alpha_choice = 0

range_invest = ends[c((start_chap),(end_chap+1)),2] # FROM where to where

y = t(data.matrix(senti_invest))[range_invest[1]:range_invest[2]]
X = t(contribution[,range_invest[1]:range_invest[2]])
fit2 = glm.fit(X,y)


lambdas <- 10^seq(2, -3, by = -.1)

cv_ridge <- cv.glmnet(X, y, alpha = alpha_choice, lambda = lambdas)

optimal_lambda <- cv_ridge$lambda.min

ridge_reg = glmnet(X,y, alpha = alpha_choice, family = 'gaussian', lambda = optimal_lambda)

beta = as.vector(ridge_reg[["beta"]])
beta = beta/norm(beta, type='2')


df <- data.frame(
  char = char[,1],
  be = beta
  )

df %>%
  ggplot(aes(x=char, y=be))+
  geom_col()+
  scale_x_discrete(guide = guide_axis(n.dodge=3))+
  labs(title="Contribution to negative sentiment", x = "Character", y="value")+
  theme_bw() + theme(axis.text.x=element_text(size=9, angle=0, vjust=0.3),
                     axis.text.y=element_text(size=9),
                     plot.title=element_text(size=11))
```

